---
title: "Troubleshooting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{troubleshooting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

# Troubleshooting:

The function was written until December 2023. I've used the current column numbers set in Purencys' software to address the required information. If these will be changed by any chance by Purency or yourself (or lab members), this should be adopted to the function as well (see the article *Change settings to other labs' preferences* above to read how).
If not, the results are, of course, not reliable any more! 

The source code can be accessed via [Github](https://github.com/Maki-science/evalPurency).
I've commented it quite sophisticated, and changes should be quite easy when you're a bit into programming. Otherwise [open an issue](https://github.com/Maki-science/evalPurency/issues) or send me a request, and I will do my best to implement your desired features.

Here are issues that may arise, or we already faced (but is out of our hands), when applying the functions:

  - If an error occurs or you get different results, each time the function runs, make sure that you have only the files in the respective folder that should be processed. If you re-run the function, you will have the previously created files there, so you need to delete them first, and then run the function again. If it's just the files, created from a previous run, there will be no error. However, the results are probably wrong! *So, always check that you have just the files of interest in the respective folder!*
  - Make sure you considered all points mentioned in the articles (see tool bar at the top), where a *WARNING* or *NOTE* was provided. For your convenience, we also gathered them below.
  - NOTE: The following case is now automated since version 1.3.7.9021. The ```startrow``` will be automatically selected for each file separately, now. However, if the following error occurs, you can disable the automation by setting a defined number for ```startrow``` as described here:
  If the error ```Error in read.table(file = file, header = header, sep = sep, quote = quote,  : more columns than column names``` occurs, it is likely caused by an excess line in the header of your *.csv file. For unkown reason, Purency once in a while creates a file that contains an additional line in its meta-data header (the first 40 or 41 lines, respektively). Usually, the real data set starts at line 41 (with the column header). However, in this case, the data start at line 42. The solution is simple: just delete one of the first 41 lines in the respective file (watch out to respect the correct decimal sign) and run the function again. Now it should run smooth, as long as there is no further file with that issue. If all files contain more or less lines, whatsoever, you can also set ```startrow = x```, while ```x``` is the number of lines, that should be ignored (i.e., the next line the data header should start). Then the function will read in the data correctly, if all files have the same structure!
  

If something does not work, you may further missed one of the Warnings stated at the respective option. We gathered all points here again:

  -   Feel free to adapt the naming of the files to your liking as long as the division with the ```_``` (underline), and the positioning of the blank in the sample name is provided. Otherwise you may get unforeseeable results!
  -   The naming of the files is an important prerequisite for a proper processing. Thus you need to cautiously set your file names!
  -   If you have named the polymers differently in your Purency software, you should set these accordingly with the parameter ```polymers```.
  -   When using ```setDivFactor```, make sure to exactly follow the instructions in the console. Keep the order similar to the provided order of the samples/blanks.
  -   If you use several blanks that should be summed for all samples you can only chose a common division factor. Otherwise estimations will be unevenly distributed over the filters, which is not recommended.
  -   ```setDivFactor``` is not available for ```evalPurency.particles()```, since it is not reasonable to multiply particles with similar properties in a particle-wise processing.
  -   ```colourSep```is not available for ```evalPurency()```, since colours are not considered in the summary function (it doesn't make sense to create even more groups as there are anyway)!
  -   ```eocsum``` is not available for ```evalPurency.particles()```.
  -   ```labpreset``` is only available after implementation of your desired setup. Please contact us via the *Report a bug* button on the right side of this page. The implementation can be done fast to get you started soon.
