test_that("No labpreset works", {
  expect_equal(eP.config.helper(labpreset = FALSE,
                                blankKey = "Blank",
                                sep = ";",
                                dec = ",",
                                colPol = 6,
                                colL = 17,
                                colReqPol = 24,
                                ReqPolKey = "ja",
                                colShape = 25,
                                colCol = 26,
                                colLFib = 27,
                                colArea = 4,
                                colWidth = 18,
                                fibre = "Faser",
                                sphere = "Kugel",
                                fragment = "Fragment",
                                pixel = "Pixel",
                                startrow = 40), 
               data.frame(
                 labname = FALSE,
                 blankKey = "Blank",
                 sep = ";",
                 dec = ",",
                 colPol = 6,
                 colL = 17,
                 colReqPol = 24,
                 ReqPolKey = "ja",
                 colShape = 25,
                 colCol = 26,
                 colLFib = 27,
                 colArea = 4,
                 colWidth = 18,
                 fibre = "Faser",
                 sphere = "Kugel",
                 fragment = "Fragment",
                 pixel = "Pixel",
                 startrow = 40
               ))
})


test_that("Set labpreset works", {
  expect_equal(eP.config.helper(labpreset = "Laforsch",
                                blankKey = "Blank",
                                sep = ";",
                                dec = ",",
                                colPol = 20,
                                colL = 17,
                                colReqPol = 18,
                                ReqPolKey = "ja",
                                colShape = 25,
                                colCol = 26,
                                colLFib = 27,
                                colArea = 4,
                                colWidth = 18,
                                fibre = "blub",
                                sphere = "Kugel",
                                fragment = "Fragment",
                                pixel = "Pixel",
                                startrow = 40), 
               data.frame(
                 labname = "Laforsch",
                 blankKey = "Blank",
                 sep = ";",
                 dec = ",",
                 colPol = 6,
                 colL = 17,
                 colReqPol = 24,
                 ReqPolKey = "ja",
                 colShape = 25,
                 colCol = 26,
                 colLFib = 27,
                 colArea = 4,
                 colWidth = 18,
                 fibre = "Faser",
                 sphere = "Kugel",
                 fragment = "Fragment",
                 pixel = "Pixel",
                 startrow = 40
               ))
})
